apiVersion: v1
kind: ConfigMap
metadata:
  name: spryker-config-common
data:
{{ include "env.common" . | indent 2}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spryker-config-cli
data:
  SPRYKER_LOG_STDOUT: "/tmp/stdout"
  SPRYKER_LOG_STDERR: "/tmp/stderr"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spryker-jenkins
data:
  spryker.sh: |-
    #!/bin/bash

    set -e
    echo "> ${COMMAND}"

    http_response=$(curl --request POST -LsS \
    -o /dev/stderr \
    -w "%{http_code}" \
    --data "APPLICATION_STORE='${APPLICATION_STORE}' COMMAND='${COMMAND}' cli.sh" \
    --max-time 1000 \
    --url "http://{{- .Values.components.cli.name -}}:{{- .Values.components.cli.port -}}/console")

    if [ "${http_response}" != "200" ]; then
    exit 1
    fi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spryker-cli-env
data:
  {{- range .Values.global.stores }}
  {{ . | lower -}}.env: |-
{{ include "env.common" $ | replace ": " "=" | indent 4}}
{{ include "secrets.common" $ | replace ": " "=" | indent 4 }}
    # Store specific variables
    APPLICATION_STORE={{- . }}
    SPRYKER_SEARCH_NAMESPACE={{- . | lower -}}_search
    SPRYKER_KEY_VALUE_STORE_NAMESPACE={{- get $.Values.components.keyValueStore.data.namespace . | quote }}
    SPRYKER_BROKER_NAMESPACE={{- . | lower -}}_queue
    SPRYKER_SESSION_BE_NAMESPACE={{- get $.Values.components.sessions.data.namespace.zed . | quote }}
    SPRYKER_SESSION_FE_NAMESPACE={{- get $.Values.components.sessions.data.namespace.yves . | quote }}
  {{- end }}
