apiVersion: v1
kind: Secret
metadata:
  name: spryker-zed-credentials
type: Opaque
stringData:
  SPRYKER_BROKER_CONNECTIONS: {{ include "brokerStoreEntries" . | quote }}
  SPRYKER_BROKER_API_USERNAME: {{ .Values.credentials.broker.apiUsername }}
  SPRYKER_BROKER_API_PASSWORD: {{ .Values.credentials.broker.password }}
  SPRYKER_BROKER_USERNAME: {{ .Values.credentials.broker.username }}
  SPRYKER_BROKER_PASSWORD: {{ .Values.credentials.broker.password }}
  SPRYKER_DB_USERNAME: "{{ .Values.credentials.database.username }}"
  SPRYKER_DB_PASSWORD: "{{ .Values.credentials.database.password }}"
  SPRYKER_DB_ROOT_USERNAME: "{{ .Values.credentials.database.rootUsername }}"
  SPRYKER_DB_ROOT_PASSWORD: "{{ .Values.credentials.database.rootPassword }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-config
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name" : "{{ .Values.credentials.broker.username }}",
          "password" : "{{ .Values.credentials.broker.password }}",
          "tags" : "administrator"
        }
      ],
      "vhosts": {{ template "brokerConfigVHosts" . }},
      "permissions": {{ template "brokerConfigPermissions" . }},
      "policies": {{ template "brokerConfigPolicies" . }}
    }
